[package]
name = "qoi-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
md-5 = "0.10.1"
zip = "0.6.2"

[profile.release]
debug = true
lto = true